//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCdr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisSpeed
    {
        public System.Guid AnalysisSpeedId { get; set; }
        public int AnalysisTypeId { get; set; }
        public System.Guid KeySequenceAnalysisId { get; set; }
        public decimal TotalTimeInMilliSec { get; set; }
        public decimal WordPerMin { get; set; }
        public decimal CharsPerSec { get; set; }
    
        public virtual AnalysisType AnalysisType { get; set; }
        public virtual KeySequenceAnalysis KeySequenceAnalysis { get; set; }
    }
}
