//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCdr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisAccuracy
    {
        public System.Guid AnalysisAccuracyId { get; set; }
        public int AnalysisTypeId { get; set; }
        public System.Guid KeySequenceAnalysisId { get; set; }
        public decimal Accuracy { get; set; }
        public int NumWords { get; set; }
        public int NumChars { get; set; }
        public int NumCorrectChars { get; set; }
        public int NumIncorrectChars { get; set; }
        public int NumExtraChars { get; set; }
        public int NumShortChars { get; set; }
    
        public virtual AnalysisType AnalysisType { get; set; }
        public virtual KeySequenceAnalysis KeySequenceAnalysises { get; set; }
    }
}
