//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCdr.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeyCommanderEntities : DbContext
    {
        public KeyCommanderEntities()
            : base("name=KeyCommanderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalysisAccuracy> AnalysisAccuracys { get; set; }
        public virtual DbSet<AnalysisSpeed> AnalysisSpeeds { get; set; }
        public virtual DbSet<AnalysisType> AnalysisTypes { get; set; }
        public virtual DbSet<KCUser> KCUsers { get; set; }
        public virtual DbSet<KeySequence> KeySequences { get; set; }
        public virtual DbSet<KeySequenceAnalysis> KeySequenceAnalysises { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SourceType> SourceTypes { get; set; }
    }
}
