//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCdr.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeyCommanderEntities1 : DbContext
    {
        public KeyCommanderEntities1()
            : base("name=KeyCommanderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalysisAccuracy> AnalysisAccuracy { get; set; }
        public virtual DbSet<AnalysisSpeed> AnalysisSpeed { get; set; }
        public virtual DbSet<AnalysisType> AnalysisType { get; set; }
        public virtual DbSet<KCUser> KCUser { get; set; }
        public virtual DbSet<KeySequences> KeySequence { get; set; }
        public virtual DbSet<KeySequenceAnalysis> KeySequenceAnalysis { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<SourceType> SourceType { get; set; }
    }
}
