//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCdr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeySequenceAnalysis
    {
        public System.Guid KeySequenceAnalysisId { get; set; }
        public System.Guid KeySequenceId { get; set; }
        public int AnalysisTypeId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual AnalysisAccuracy AnalysisAccuracy { get; set; }
        public virtual AnalysisSpeed AnalysisSpeed { get; set; }
        public virtual AnalysisType AnalysisType { get; set; }
        public virtual KeySequence KeySequence { get; set; }
    }
}
