//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCdr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeySequences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeySequences()
        {
            this.KeySequenceAnalysis = new HashSet<KeySequenceAnalysis>();
        }
    
        public System.Guid KeySequenceId { get; set; }
        public System.Guid SessionId { get; set; }
        public int SourceTypeId { get; set; }
        public string SourceKey { get; set; }
        public string TextShown { get; set; }
        public string TextEntered { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual SourceType SourceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeySequenceAnalysis> KeySequenceAnalysis { get; set; }
    }
}
